import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock the db module
vi.mock('@/lib/db', () => ({
  prisma: {},
}))

describe('ensureLineups - Auto-Generate (AC2)', () => {
  let mockTx: any
  let mockTeam: any
  let mockTeamPlayers: any[]

  beforeEach(() => {

    // Set up mock team players with varying purchase prices
    mockTeamPlayers = [
      { id: 'p1', playerId: 'pid1', teamId: 'team1', leagueId: 'league1', purchasePrice: 10.0, player: { id: 'pid1', fullname: 'Player 1' } },
      { id: 'p2', playerId: 'pid2', teamId: 'team1', leagueId: 'league1', purchasePrice: 9.5, player: { id: 'pid2', fullname: 'Player 2' } },
      { id: 'p3', playerId: 'pid3', teamId: 'team1', leagueId: 'league1', purchasePrice: 9.0, player: { id: 'pid3', fullname: 'Player 3' } },
      { id: 'p4', playerId: 'pid4', teamId: 'team1', leagueId: 'league1', purchasePrice: 8.5, player: { id: 'pid4', fullname: 'Player 4' } },
      { id: 'p5', playerId: 'pid5', teamId: 'team1', leagueId: 'league1', purchasePrice: 8.0, player: { id: 'pid5', fullname: 'Player 5' } },
      { id: 'p6', playerId: 'pid6', teamId: 'team1', leagueId: 'league1', purchasePrice: 7.5, player: { id: 'pid6', fullname: 'Player 6' } },
      { id: 'p7', playerId: 'pid7', teamId: 'team1', leagueId: 'league1', purchasePrice: 7.0, player: { id: 'pid7', fullname: 'Player 7' } },
      { id: 'p8', playerId: 'pid8', teamId: 'team1', leagueId: 'league1', purchasePrice: 6.5, player: { id: 'pid8', fullname: 'Player 8' } },
      { id: 'p9', playerId: 'pid9', teamId: 'team1', leagueId: 'league1', purchasePrice: 6.0, player: { id: 'pid9', fullname: 'Player 9' } },
      { id: 'p10', playerId: 'pid10', teamId: 'team1', leagueId: 'league1', purchasePrice: 5.5, player: { id: 'pid10', fullname: 'Player 10' } },
      { id: 'p11', playerId: 'pid11', teamId: 'team1', leagueId: 'league1', purchasePrice: 5.0, player: { id: 'pid11', fullname: 'Player 11' } },
      { id: 'p12', playerId: 'pid12', teamId: 'team1', leagueId: 'league1', purchasePrice: 4.5, player: { id: 'pid12', fullname: 'Player 12' } },
      { id: 'p13', playerId: 'pid13', teamId: 'team1', leagueId: 'league1', purchasePrice: 4.0, player: { id: 'pid13', fullname: 'Player 13' } },
      { id: 'p14', playerId: 'pid14', teamId: 'team1', leagueId: 'league1', purchasePrice: 3.5, player: { id: 'pid14', fullname: 'Player 14' } },
      { id: 'p15', playerId: 'pid15', teamId: 'team1', leagueId: 'league1', purchasePrice: 3.0, player: { id: 'pid15', fullname: 'Player 15' } },
    ]

    // Set up base mock transaction object
    mockTx = {
      teamPlayer: {
        findMany: vi.fn(),
      },
      lineup: {
        create: vi.fn(),
        findFirst: vi.fn().mockResolvedValue(null), // No previous lineup
      },
    }

    // Set up team with no lineups initially
    mockTeam = {
      id: 'team1',
      name: 'Test Team',
      lineups: [],
    }
  })

  it('AC2.1 + AC2.2 + AC2.3 + AC2.4: Auto-generate creates lineup from squad with correct slot types and roles', async () => {
    // Setup: team has no lineups, but has 15 players
    mockTx.teamPlayer.findMany.mockResolvedValue(mockTeamPlayers)

    const createdLineup = {
      id: 'lineup1',
      gameweekId: 'gw1',
      teamId: 'team1',
      slots: [
        // XI slots (top 11)
        { playerId: 'pid1', slotType: 'XI', role: 'CAPTAIN', benchPriority: null },
        { playerId: 'pid2', slotType: 'XI', role: 'VC', benchPriority: null },
        { playerId: 'pid3', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid4', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid5', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid6', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid7', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid8', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid9', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid10', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid11', slotType: 'XI', role: null, benchPriority: null },
        // BENCH slots (bottom 4)
        { playerId: 'pid12', slotType: 'BENCH', role: null, benchPriority: 1 },
        { playerId: 'pid13', slotType: 'BENCH', role: null, benchPriority: 2 },
        { playerId: 'pid14', slotType: 'BENCH', role: null, benchPriority: 3 },
        { playerId: 'pid15', slotType: 'BENCH', role: null, benchPriority: 4 },
      ],
    }

    mockTx.lineup.create.mockResolvedValue(createdLineup)

    // Import the function
    const { ensureLineups } = await import('@/lib/scoring/pipeline')

    // Call the function
    const result = await ensureLineups(mockTx, [mockTeam], 'gw1')

    // Verify: auto-generated lineup was created
    expect(mockTx.lineup.create).toHaveBeenCalled()
    expect(result.autoGenerated).toBe(1)

    // Verify the created lineup was added to team.lineups
    expect(mockTeam.lineups).toHaveLength(1)

    // Verify the actual arguments passed to tx.lineup.create
    const createCall = mockTx.lineup.create.mock.calls[0][0]
    const slots = createCall.data.slots.createMany.data

    expect(slots).toHaveLength(15)

    // Verify XI + BENCH split
    const xiSlots = slots.filter((s: any) => s.slotType === 'XI')
    const benchSlots = slots.filter((s: any) => s.slotType === 'BENCH')

    expect(xiSlots).toHaveLength(11)
    expect(benchSlots).toHaveLength(4)

    // Verify captain is highest price (pid1 = 10.0)
    const captain = slots.find((s: any) => s.role === 'CAPTAIN')
    expect(captain?.playerId).toBe('pid1')
    expect(captain?.slotType).toBe('XI')

    // Verify VC is second highest (pid2 = 9.5)
    const vc = slots.find((s: any) => s.role === 'VC')
    expect(vc?.playerId).toBe('pid2')
    expect(vc?.slotType).toBe('XI')

    // Verify bench priorities descending by price
    expect(benchSlots[0].benchPriority).toBe(1)
    expect(benchSlots[0].playerId).toBe('pid12') // price 4.5
    expect(benchSlots[1].benchPriority).toBe(2)
    expect(benchSlots[1].playerId).toBe('pid13') // price 4.0
    expect(benchSlots[2].benchPriority).toBe(3)
    expect(benchSlots[2].playerId).toBe('pid14') // price 3.5
    expect(benchSlots[3].benchPriority).toBe(4)
    expect(benchSlots[3].playerId).toBe('pid15') // price 3.0
  })

  it('AC2.5: Team with empty squad is skipped', async () => {
    // Setup: team has no squad
    mockTx.teamPlayer.findMany.mockResolvedValue([])

    const { ensureLineups } = await import('@/lib/scoring/pipeline')
    const result = await ensureLineups(mockTx, [mockTeam], 'gw1')

    // Verify: no lineup created, autoGenerated = 0
    expect(mockTx.lineup.create).not.toHaveBeenCalled()
    expect(result.autoGenerated).toBe(0)
    expect(mockTeam.lineups).toHaveLength(0)
  })

  it('AC2.6: Team that already has a lineup in array is not auto-generated', async () => {
    // Setup: team already has a lineup (from carry-forward)
    mockTeam.lineups = [{ id: 'carried-lineup', gameweekId: 'gw1', slots: [] }]
    mockTx.teamPlayer.findMany.mockResolvedValue(mockTeamPlayers)

    const { ensureLineups } = await import('@/lib/scoring/pipeline')
    const result = await ensureLineups(mockTx, [mockTeam], 'gw1')

    // Verify: no additional lineup created
    expect(mockTx.lineup.create).not.toHaveBeenCalled()
    expect(result.autoGenerated).toBe(0)
    expect(mockTeam.lineups).toHaveLength(1) // Still just the carry-forward
  })

  it('AC2.4: Bench priority assigns 1-4 in descending price order', async () => {
    // Setup: verify bench priorities are correct
    mockTx.teamPlayer.findMany.mockResolvedValue(mockTeamPlayers)

    const createdLineup = {
      id: 'lineup1',
      gameweekId: 'gw1',
      teamId: 'team1',
      slots: [
        { playerId: 'pid1', slotType: 'XI', role: 'CAPTAIN', benchPriority: null },
        { playerId: 'pid2', slotType: 'XI', role: 'VC', benchPriority: null },
        { playerId: 'pid3', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid4', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid5', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid6', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid7', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid8', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid9', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid10', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid11', slotType: 'XI', role: null, benchPriority: null },
        { playerId: 'pid12', slotType: 'BENCH', role: null, benchPriority: 1 },
        { playerId: 'pid13', slotType: 'BENCH', role: null, benchPriority: 2 },
        { playerId: 'pid14', slotType: 'BENCH', role: null, benchPriority: 3 },
        { playerId: 'pid15', slotType: 'BENCH', role: null, benchPriority: 4 },
      ],
    }

    mockTx.lineup.create.mockResolvedValue(createdLineup)

    const { ensureLineups } = await import('@/lib/scoring/pipeline')
    const result = await ensureLineups(mockTx, [mockTeam], 'gw1')

    // Verify the actual arguments passed to tx.lineup.create
    const createCall = mockTx.lineup.create.mock.calls[0][0]
    const slots = createCall.data.slots.createMany.data

    // Verify bench priorities are sequential 1-4
    const benchSlots = slots.filter((s: any) => s.slotType === 'BENCH')
    const priorities = benchSlots.map((s: any) => s.benchPriority)
    expect(priorities).toEqual([1, 2, 3, 4])
  })
})
